<template>
  <button
    class="
      flex
      items-center
      justify-center
      rounded-md
      bg-primary-500
      px-4
      py-2
      text-sm
      font-medium
      text-white
      hover:bg-primary-600
      focus:outline-none
      focus:ring-4
      focus:ring-primary-300
      dark:bg-primary-600
      dark:hover:bg-primary-700
      dark:focus:ring-primary-800
    ">Click me</button>
</template>