// utils/errors/errorCodes.ts
export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN: 'UNKNOWN_ERROR',
  REACTIVE_CONTINUITY_ERROR: 'REACTIVE_CONTINUITY_ERROR',
  DB_CONTINUITY_ERROR: 'DB_CONTINUITY_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];