/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Map: typeof import('./components/Map.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    RouteBar: typeof import('./components/route/RouteBar.vue')['default']
    RouteInfos: typeof import('./components/route/RouteInfos.vue')['default']
    RouteMarker: typeof import('./components/route/RouteMarker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteUI: typeof import('./components/route/RouteUI.vue')['default']
    Searchbar: typeof import('./components/layout/Searchbar.vue')['default']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
  }
}
